
#ifndef _C1_co33_
#define _C1_co33_

#ifdef __cplusplus
extern "C" {
#endif

static EIF_REFERENCE F39_816_body(EIF_REFERENCE);
extern EIF_REFERENCE F39_816(EIF_REFERENCE);
static EIF_REFERENCE F39_817_body(EIF_REFERENCE);
extern EIF_REFERENCE F39_817(EIF_REFERENCE);
static EIF_REFERENCE F39_818_body(EIF_REFERENCE);
extern EIF_REFERENCE F39_818(EIF_REFERENCE);
static EIF_REFERENCE F39_819_body(EIF_REFERENCE);
extern EIF_REFERENCE F39_819(EIF_REFERENCE);
extern void EIF_Minit33(void);
extern void F624_4071(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F629_4137(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_REFERENCE F20_49(EIF_REFERENCE);
extern EIF_REFERENCE F20_48(EIF_REFERENCE);
extern EIF_REFERENCE F20_47(EIF_REFERENCE);
extern EIF_REFERENCE F20_54(EIF_REFERENCE);
extern EIF_REFERENCE F908_6910(EIF_REFERENCE);
extern EIF_REFERENCE F20_53(EIF_REFERENCE);
extern EIF_REFERENCE F20_52(EIF_REFERENCE);
extern EIF_REFERENCE F20_51(EIF_REFERENCE);
extern EIF_REFERENCE F20_50(EIF_REFERENCE);

#ifdef __cplusplus
}
#endif

#endif
