
#ifndef _C1_sy19_
#define _C1_sy19_

#ifdef __cplusplus
extern "C" {
#endif

static EIF_REFERENCE F27_214_body(EIF_REFERENCE);
extern EIF_REFERENCE F27_214(EIF_REFERENCE);
static EIF_REFERENCE F27_215_body(EIF_REFERENCE);
extern EIF_REFERENCE F27_215(EIF_REFERENCE);
static EIF_REFERENCE F27_216_body(EIF_REFERENCE);
extern EIF_REFERENCE F27_216(EIF_REFERENCE);
static EIF_REFERENCE F27_217_body(EIF_REFERENCE);
extern EIF_REFERENCE F27_217(EIF_REFERENCE);
static EIF_REFERENCE F27_218_body(EIF_REFERENCE);
extern EIF_REFERENCE F27_218(EIF_REFERENCE);
static EIF_REFERENCE F27_219_body(EIF_REFERENCE);
extern EIF_REFERENCE F27_219(EIF_REFERENCE);
static EIF_REFERENCE F27_220_body(EIF_REFERENCE);
extern EIF_REFERENCE F27_220(EIF_REFERENCE);
extern void EIF_Minit19(void);
extern EIF_REFERENCE F20_49(EIF_REFERENCE);
extern EIF_REFERENCE F20_48(EIF_REFERENCE);
extern EIF_REFERENCE F41_887(EIF_REFERENCE);
extern EIF_REFERENCE F41_886(EIF_REFERENCE);
extern void F33_801(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F41_885(EIF_REFERENCE);
extern EIF_REFERENCE F20_50(EIF_REFERENCE);

#ifdef __cplusplus
}
#endif

#endif
